### PR TITLE
Added some files from the git course

### PR DESCRIPTION
**Pull request by Zeeatree**
playing around

### CODE REVIEW

**Review by wardahafeez2920 — APPROVED** [review]
Looks very good and neat

**Review by Awzel — COMMENTED** [review]
Looks amazing~ Great work~

**Comment by Zeeatree** [comment]
hahahah I wish our job will be this easy

**Comment by wardahafeez2920** [comment]
Everything looks good, you can do the merge

**Comment by Zeeatree** [comment]
thank u.

**Comment by agil1402b** [comment]
Looks good.

**Comment by agil1402b** [comment]
looks good.

**Pull request merged**
